/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Color;
import javax.swing.ImageIcon;
/**
 *
 * @author NUD-Student
 */
public class frm_1 extends javax.swing.JFrame {

    /**
     * Creates new form frm_1
     */
    public frm_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_Rock = new javax.swing.JButton();
        btn_Paper = new javax.swing.JButton();
        btn_Scissors = new javax.swing.JButton();
        lblComputer = new javax.swing.JLabel();
        lblPlayer = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        lblComp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("COMPUTER");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel2.setText("Player");

        btn_Rock.setIcon(new javax.swing.ImageIcon("C:\\Users\\NUD-Student\\Downloads\\Bato.png")); // NOI18N
        btn_Rock.setText("Rock");
        btn_Rock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RockActionPerformed(evt);
            }
        });

        btn_Paper.setIcon(new javax.swing.ImageIcon("C:\\Users\\NUD-Student\\Downloads\\Papel.png")); // NOI18N
        btn_Paper.setText("Paper");
        btn_Paper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PaperActionPerformed(evt);
            }
        });

        btn_Scissors.setIcon(new javax.swing.ImageIcon("C:\\Users\\NUD-Student\\Downloads\\Gunting.png")); // NOI18N
        btn_Scissors.setText("Scissors");
        btn_Scissors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ScissorsActionPerformed(evt);
            }
        });

        lblComputer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblComputer.setText("Computer");

        lblPlayer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPlayer.setText("Player");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("SCORE");

        lblResult.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblResult.setText("RESULT");

        lblComp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblComp.setForeground(new java.awt.Color(255, 153, 153));
        lblComp.setText("              ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(lblComp, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(184, 184, 184))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblResult)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlayer)
                            .addComponent(lblComputer))
                        .addGap(136, 136, 136))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Rock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(btn_Paper)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(btn_Scissors)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblComp, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblComputer)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlayer)
                    .addComponent(lblResult))
                .addGap(46, 46, 46)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Rock)
                    .addComponent(btn_Paper)
                    .addComponent(btn_Scissors))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int player, computer, player_score = 0, computer_score = 0;
    
    void generateComputer() {

        computer = (int) (Math.random() * 3 + 1);

        if (computer == 1) {

            lblComp.setIcon(new ImageIcon("C:\\Users\\NUD-Student\\Downloads\\Bato.png")); 

        } else if (computer == 2) {

            lblComp.setIcon(new ImageIcon("C:\\Users\\NUD-Student\\Downloads\\Papel.png")); 

        } else if (computer == 3) {

            lblComp.setIcon(new ImageIcon("C:\\Users\\NUD-Student\\Downloads\\Gunting.png")); 

        }

    }
    
    void resetColors(){
        btn_Rock.setBackground(Color.gray);
        btn_Paper.setBackground(Color.gray);
        btn_Scissors.setBackground(Color.gray);
    }
    
    void checkResult(){
         if (player == computer) {

        lblResult.setText("Draw!");

    } else if ((player == 1 && computer == 2) || (player == 2 && computer == 3) || (player == 3 && computer == 1)) {

        lblResult.setText("You Lose! Computer Wins!");

        computer_score++;

    } else {

        lblResult.setText("You Win! Computer Loses!");

        player_score++;

    }

    lblPlayer.setText("Player Score: " + player_score);

    lblComputer.setText("Computer Score: " + computer_score);

}
    private void btn_RockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RockActionPerformed
   generateComputer();
   resetColors();
   btn_Rock.setBackground(Color.blue);
   player = 1;
   checkResult();
  
    }//GEN-LAST:event_btn_RockActionPerformed

    private void btn_ScissorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ScissorsActionPerformed
   generateComputer();
   resetColors();
   btn_Scissors.setBackground(Color.blue);
   player = 3;
   checkResult();
    }//GEN-LAST:event_btn_ScissorsActionPerformed

    private void btn_PaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PaperActionPerformed
   generateComputer();
   resetColors();
   btn_Paper.setBackground(Color.blue);
   player = 2;
   checkResult();
    }//GEN-LAST:event_btn_PaperActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Paper;
    private javax.swing.JButton btn_Rock;
    private javax.swing.JButton btn_Scissors;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblComp;
    private javax.swing.JLabel lblComputer;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JLabel lblResult;
    // End of variables declaration//GEN-END:variables
}
